name: flutter_background_service_plus
repository: https://github.com/EsbenSoeltoft/flutter_background_service_plus

packages:
  - packages/**

command:
  version:
    # Generate commit links in package changelogs.
    linkToCommits: true
    # Only allow versioning to happen on main branch.
    branch: master
    # Additionally build a changelog at the root of the workspace.
    workspaceChangelog: true

scripts:
  # Wire all local path dependencies between packages
  bootstrap: melos bootstrap

  # Clean every package then run `flutter clean` in each
  clean: |
    melos clean
    melos run postclean

  postclean: >
    melos exec -c 6 -- "flutter clean"

  # Run analyzer across all packages
  analyze: melos exec -c 6 -- "flutter analyze"

  # Format all Dart code
  format: melos exec -c 6 -- "dart format ."

  # Run tests across packages (if/when you add tests)
  test: melos exec -c 6 -- "flutter test"
